volumes:
  dvwa:

networks:
  dvwa:

services:
  dvwa81-deb04:
    build: .
    image: ghcr.io/digininja/dvwa:latest
    container_name: dvwa81-deb04
    # Change `always` to `build` to build from local source
    pull_policy: always
    environment:
      - DB_SERVER=db
    depends_on:
      - db
    # Uncomment the next 2 lines to serve local source
    # volumes:
    #   - ./:/var/www/html
    networks:
      - dvwa
    ports:
      - 4281:80
    restart: unless-stopped

  dvwa82-deb04:
    build: .
    image: ghcr.io/digininja/dvwa:latest
    container_name: dvwa82-deb04
    # Change `always` to `build` to build from local source
    pull_policy: always
    environment:
      - DB_SERVER=db
    depends_on:
      - db
    # Uncomment the next 2 lines to serve local source
    # volumes:
    #   - ./:/var/www/html
    networks:
      - dvwa
    ports:
      - 4282:80
    restart: unless-stopped

  db:
    image: docker.io/library/mariadb:10
    container_name: db-deb04
    environment:
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      - dvwa:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro  
    networks:
      - dvwa
    restart: unless-stopped
